name: example
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.1.4
  in_app_review: 2.0.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter
  rate_app_dialog:
    path: ../

flutter: 
  uses-material-design: true