name: rate_app_dialog
version: 0.1.3
homepage: https://github.com/kellvembarbosa/rate_app_dialog
description: This package is designed to increase the ratings in your app, with bad review filter, find out what's bad and get more positive reviews!
environment: 
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies: 
  rflutter_alert: 2.0.2
  shared_preferences: 2.0.6
  in_app_review: 2.0.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

